name: tagbasics
description: "Basico!"
version: 0.4.0
homepage: "https://www.tagliadev.tech"

environment:
  sdk: ^3.8.1
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0+1
  equatable: ^2.0.7
  hive_flutter: ^1.1.0
  intl: ^0.20.2
  flutter_riverpod: ^2.6.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

